//system
#macro __FHAUDIO_VOLUMES_FILE "fhAudioVolumes.fha"
#macro __FHAUDIO_MAGIC_STRING "FHAUDIO"

//track status
#macro __FHAUDIO_STATUS_STOPPED 0
#macro __FHAUDIO_STATUS_PLAYING 1
#macro __FHAUDIO_STATUS_PAUSED 2
#macro __FHAUDIO_STATUS_CROSSFADING 3
#macro __FHAUDIO_STATUS_SWAPFADING 4

//sound choosing stuff
#macro __FHAUDIO_NUM_CHOOSE_BEHAVIORS 3